### ISSUE TITLE
Disable Scrolling Backwards in Time 

### ISSUE THREAD

**Issue by alexcalkins** [jackowski/MJCalendar#1]
Thanks again for the great work on this repository Michal! This calendar component works great as a date picker, but it would be nice if there was a way to prevent the user from being able to scroll prior to the current date if you're using the week views and set the first date to be the current date. I've made a workaround to launch an alert and cancel selection if the user tries to select an older date, but being able to restrict this in the UI would be ideal.

**Comment by jackowski** [comment]
Thank you Alex for suggesting useful improvement. It's on my to do list now!

**Comment by jackowski** [comment]
Resolved in 0.2.0 release.
